// testin
public class OMathOperations2 {
  /**
   * @description Multiplies 5 and 5 together.
   * @return Integer The product of 5 * 5.
   */
  public static Integer mulFiveAndFive() {
    Integer a = 5;
    Integer b = 5;
    Integer result = a * b;
    return result;
  }

  /**
   * @description Adds 5 and 5 together.
   * @return Integer The sum of 5 + 5.
   */
  public static Integer addFiveAndFive() {
    Integer a = 5;
    Integer b = 5;
    Integer result = a + b;
    return result;
  }
}
