public class OMathOperations {
  /**
  * @description Adds 5 and 5 together.
  * @return Integer The sum of 5 + 5...
  */
  public static Integer addFiveAndFive() {
    Integer a = 5;
    Integer b = 5;
    Integer result = a + b;
    return result;
  }

  /**
  * @description Subtracts 5 from 5.
  * @return Integer The result of 5 - 5...
  */
  public static Integer subFiveAndFive() {
    Integer a = 5;
    Integer b = 5;
    Integer result = a - b;
    return result;
  }
}